CREATE OR REPLACE TYPE ENGINEER_T AS VARRAY (2) OF VARCHAR(30);

CREATE OR REPLACE TYPE BOSS_T AS OBJECT (
  boss_id   NUMBER,
  boss_name VARCHAR2(30),
  phone     VARCHAR(9)
);

CREATE OR REPLACE TYPE BLUEPRINT_T AS OBJECT (
  blueprint_id NUMBER,
  title        VARCHAR2(255),
  engineers    ENGINEER_T
);

CREATE OR REPLACE TYPE BLUEPRINTS_NT AS TABLE OF BLUEPRINT_T;

CREATE TABLE PROJECT_BOSSES_TAB OF BOSS_T;

CREATE TABLE PROJECTS_TAB (
  project_name VARCHAR2(255),
  due_date     DATE,
  project_boss BOSS_T,
  blueprints   BLUEPRINTS_NT
)
  NESTED TABLE blueprints STORE AS BLUEPRINTS_TAB;